//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint6_Pellitero_Carles
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveBeacon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActiveBeacon()
        {
            this.RouteTraffics = new HashSet<RouteTraffic>();
        }
    
        public int idActiveBeacon { get; set; }
        public string codeBeacon { get; set; }
        public string descBeacon { get; set; }
        public Nullable<int> IdRoute { get; set; }
        public string Sector { get; set; }
        public string Remarks { get; set; }
    
        public virtual Route Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteTraffic> RouteTraffics { get; set; }
    }
}
