//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint6_Pellitero_Carles
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminCoordinate
    {
        public int idCoordinate { get; set; }
        public string Coordinate { get; set; }
        public string ValueCoord { get; set; }
    }
}
