//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint6_Pellitero_Carles
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int idBlacklist { get; set; }
        public string codeShip { get; set; }
        public string descShip { get; set; }
        public string ShipTransponder { get; set; }
        public string Remarks { get; set; }
    }
}
