//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint6_Pellitero_Carles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DarkCoreEntities : DbContext
    {
        public DarkCoreEntities()
            : base("name=DarkCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveBeacons> ActiveBeacons { get; set; }
        public virtual DbSet<AdminCoordinates> AdminCoordinates { get; set; }
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<CodeChain> CodeChain { get; set; }
        public virtual DbSet<MessiUsers> MessiUsers { get; set; }
        public virtual DbSet<PassiveBeacons> PassiveBeacons { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<RouteTraffic> RouteTraffic { get; set; }
        public virtual DbSet<ShipTypes> ShipTypes { get; set; }
        public virtual DbSet<TrustedDevices> TrustedDevices { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
