//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint6_Pellitero_Carles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DarkCoreEntitiesMoha : DbContext
    {
        public DarkCoreEntitiesMoha()
            : base("name=DarkCoreEntitiesMoha")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveBeacon> ActiveBeacons { get; set; }
        public virtual DbSet<AdminCoordinate> AdminCoordinates { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<BlackList> BlackLists { get; set; }
        public virtual DbSet<CodeChain> CodeChains { get; set; }
        public virtual DbSet<MessiUser> MessiUsers { get; set; }
        public virtual DbSet<PassiveBeacon> PassiveBeacons { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteTraffic> RouteTraffics { get; set; }
        public virtual DbSet<ShipType> ShipTypes { get; set; }
        public virtual DbSet<TrustedDevice> TrustedDevices { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
