//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint6_Pellitero_Carles
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassiveBeacons
    {
        public int idPassiveBeacon { get; set; }
        public Nullable<int> Cicles { get; set; }
        public Nullable<int> Divisor { get; set; }
        public string DescBeacon { get; set; }
        public string Mapposition { get; set; }
    }
}
