//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint6_Pellitero_Carles
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteTraffic
    {
        public int idRouteTraffic { get; set; }
        public Nullable<int> idBeacon { get; set; }
        public string ShipTransponder { get; set; }
        public Nullable<System.DateTime> TrafficDate { get; set; }
        public Nullable<int> idTypeShip { get; set; }
        public Nullable<bool> AuthorizedAccess { get; set; }
    
        public virtual ActiveBeacons ActiveBeacons { get; set; }
    }
}
